### ISSUE TITLE
Cmake error in SIBR viewers

### ISSUE THREAD

**Issue by mkjjang3598** [graphdeco-inria/gaussian-splatting#435]
After entering `cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release` in ubuntu 20.04, I've got build errors as following. 
```

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /bin/git (found version "2.25.1") 
-- Git found: /bin/git
-- SIBR version :
 BRANCH HEAD
 COMMIT_HASH 4ae964a267cd7a844d9766563cf9d0b500131a22
 TAG 
 VERSION 0.9.6-142-g4ae964a
-- Install path set to /home/minkwan/Desktop/3dvision/research/followups/nerf/gaussian-splatting/SIBR_viewers/install.
Note you can provide default program options for Visual Studio target properties by either setting a value for the cmake cached variable 'SIBR_PROGRAMARGS' or by setting a new environment variable 'SIBR_PROGRAMARGS'
-- 

****************** Handling core dependencies ******************
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found PkgConfig: /bin/pkg-config (found version "0.29.1") 
-- Performing Test HAVE_EGL
-- Performing Test HAVE_EGL - Success
Activating EGL support for headless GLFW/GLEW
There is no provided GLEW library for your compiler, relying on find_package to find it
-- FindGLEW: did not find GLEW CMake config file. Searching for libraries.
-- FindGLEW: GLEW_USE_STATIC_LIBS is undefined. Treated as FALSE.
-- FindGLEW: GLEW_INCLUDE_DIR: /usr/include
-- FindGLEW: GLEW_INCLUDE_DIRS: /usr/include
-- FindGLEW: CMAKE_FIND_LIBRARY_SUFFIXES for SHARED: .so;.a
-- FindGLEW: CMAKE_FIND_LIBRARY_SUFFIXES for STATIC: .so
-- FindGLEW: GLEW_SHARED_LIBRARY_RELEASE: /usr/lib/x86_64-linux-gnu/libGLEW.so
-- FindGLEW: GLEW_STATIC_LIBRARY_RELEASE: GLEW_STATIC_LIBRARY_RELEASE-NOTFOUND
-- FindGLEW: GLEW_SHARED_LIBRARY_DEBUG: GLEW_SHARED_LIBRARY_DEBUG-NOTFOUND
-- FindGLEW: GLEW_STATIC_LIBRARY_DEBUG: GLEW_STATIC_LIBRARY_DEBUG-NOTFOUND
-- FindGLEW: GLEW_SHARED_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLEW.so
-- FindGLEW: GLEW_STATIC_LIBRARY: GLEW_STATIC_LIBRARY-NOTFOUND
-- FindGLEW: GLEW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libGLEW.so
-- FindGLEW: GLEW_VERSION_MAJOR: 2
-- FindGLEW: GLEW_VERSION_MINOR: 1
-- FindGLEW: GLEW_VERSION_MICRO: 0
-- FindGLEW: GLEW_VERSION: 2.1.0
-- Found GLEW: /usr/include (found version "2.1.0") 
-- FindGLEW: Creating GLEW::glew imported target.
-- FindGLEW: Creating GLEW::GLEW imported target.
There is no provided ASSIMP library for your compiler, relying on find_package to find it
NO ASSIMP DIR ASSIMP_DIR
SETTING ASSIMP DIR ASSIMP_DIR
ASSIMP DIR ASSIMP_DIR
-- Found ASSIMP: /usr/include  
-- Found FFMPEG: /usr/include/x86_64-linux-gnu  
CMake Warning at cmake/linux/dependencies.cmake:127 (find_package):
  By not providing "Findembree.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "embree", but
  CMake did not find one.

  Could not find a package configuration file provided by "embree" (requested
  version 3.0) with any of the following names:

    embreeConfig.cmake
    embree-config.cmake

  Add the installation prefix of "embree" to CMAKE_PREFIX_PATH or set
  "embree_DIR" to a directory containing one of the above files.  If "embree"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/linux/include_once.cmake:20 (include)
  src/CMakeLists.txt:46 (include_once)


-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.65.0") found components: system chrono filesystem date_time 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
There is no provided OpenCV library for your compiler, relying on find_package to find it
-- Found OpenCV: /usr (found suitable version "4.2.0", minimum required is "4.2") 
-- Library imgui already available, skipping.
-- Library nativefiledialog already available, skipping.
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.20
-- Library mrf already available, skipping.
-- Library nanoflann already available, skipping.
-- Library picojson already available, skipping.
-- Library rapidxml already available, skipping.
-- Library xatlas already available, skipping.
-- ****************************************************************


-- Adding dataset_tools project
-- BUILD_IBR_DATASET_TOOLS is OFF
-- Adding ulr project
-- BUILD_IBR_ULR is OFF
-- Adding basic project
-- BUILD_IBR_BASIC is ON
-- Adding gaussianviewer project
-- BUILD_IBR_GAUSSIANVIEWER is ON
-- Library CudaRasterizer already available, skipping.
-- The CUDA compiler identification is NVIDIA 11.3.58
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: /usr/local/cuda-11.3/include (found version "11.3.58") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Adding remote project
-- BUILD_IBR_REMOTE is ON
-- Configuring done
CMake Error in src/core/system/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/graphics/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/renderer/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/view/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/scene/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/assets/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/core/imgproc/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/basic/apps/texturedMesh/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/basic/apps/pointBased/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/basic/renderer/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/gaussianviewer/apps/gaussianViewer/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/gaussianviewer/renderer/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/remote/apps/remoteGaussianUI/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/projects/remote/renderer/CMakeLists.txt:
  Imported target "Boost::system" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Any help will be appreciated!

**Comment by jaco001** [comment]
Any help ;)
https://github.com/graphdeco-inria/gaussian-splatting#pre-built-windows-binaries

**Comment by zyzn** [comment]
I have the same problem. Have you solved it? @mkjjang3598

**Comment by WeihongPan** [comment]
Same problem.

**Comment by mkjjang3598** [comment]
I don't know the reason.. but my problem has been solved after updating to the recent code.

**Comment by zhirui-gao** [comment]
I make it success by simply add one line in the Cmakelist.txt
set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")

**Comment by tapowanliwuyun** [comment]
Same problem.

**Comment by tapowanliwuyun** [comment]
cmake  update to 3.26 ，ok

**Comment by eternalland** [comment]
> I make it success by simply add one line in the Cmakelist.txt set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")

Hello, could you clarify which 'cmakeLists.txt' file you are referring to? Is it the one in the path '/gaussian-splatting/SIBR_viewers'? Even after adding the phrase 'set(CMAKE_CUDA_COMPILER "/usr/local/cuda/bin/nvcc")' as you suggested, it still doesn't succeed.

**Comment by eternalland** [comment]
Is somebody resolve this problem? please

**Comment by eternalland** [comment]
I spent a lot of time and tried numerous methods to solve this problem, including modifying the original CMake code, but ultimately, I failed. However, I finally succeeded with a simple and efficient solution by placing the Boost files in the specified path: '/include'. Here are the steps I followed:
1. Run `locate boost/version.hpp` to find the Boost installation path. In my case, the path was /usr/include/boost/version.hpp.
2. Use `ls /usr/include/boost` to check if the 'system' component exists.
3. If the /include directory does not exist, create it using `sudo mkdir /include`.
4. Copy the Boost files to /include with `sudo cp -r /usr/include/boost/ /include/`.
5. Verify the copy was successful by running `ls /include/boost`.
6. Finally, run `cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release` to configure the build.

**Comment by yiwenshen92** [comment]
same problem, and changing CMakeLists.txt or using the Boost thing didn't help either
